[technote]
id = "DMTN-326"
series_id = "DMTN"
canonical_url = "https://dmtn-326.lsst.io"
github_url = "https://github.com/lsst-dm/dmtn-326"
github_default_branch = "main"
date_created = 2025-09-26T21:29:51Z
doi = "https://doi.org/10.71929/rubin/3399549"
organization.name = "NSF-DOE Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
internal_id = "jennesst"
orcid = "https://orcid.org/0000-0001-5982-167X"
name = {given = "Tim", family = "Jenness"}
[[technote.authors.affiliations]]
name = "NSF-DOE Vera C. Rubin Observatory / NSF NOIRLab"
internal_id = "RubinObs"
address = "Tucson"
ror = "https://ror.org/048g3cy84"
[[technote.authors]]
name = {given = "Gregory P.", family = "Dubois-Felsmann"}
internal_id = "duboisfelsmanngp"
orcid = "https://orcid.org/0000-0003-1598-6979"
[[technote.authors.affiliations]]
name = "California Institute of Technology"
internal_id = "IPAC"
ror = "https://ror.org/05q79g396"
[[technote.authors]]
name = {given = "James F.", family = "Bosch"}
internal_id = "boschjf"
orcid = "https://orcid.org/0000-0003-2759-5764"
[[technote.authors.affiliations]]
name = "Princeton University"
internal_id = "Princeton-Astro"
ror = "https://ror.org/00hx57361"
